### ISSUE TITLE
UnboundLocalError: local variable 'img_shape' referenced before assignment

### ISSUE THREAD

**Issue by willeett** [bvnayak/stereo_calibration#6]
Hi,

I am trying to run the code using Visual Studio Code in Anaconda. I am getting an error.

Traceback (most recent call last):
File "c:/Users/William/hello/_runscript.py", line 5, in
cal = StereoCalibration(r'C:\Users\William\hello\images')
File "c:\Users\William\hello\camera_calibration.py", line 25, in init
self.read_images(self.cal_path)
File "c:\Users\William\hello\camera_calibration.py", line 71, in read_images
self.objpoints, self.imgpoints_l, img_shape, None, None)
UnboundLocalError: local variable 'img_shape' referenced before assignment

Anyone know what might be the cause of this error?

Best regards

**Comment by L1ghtZz** [comment]
me too

**Comment by mmt93** [comment]
It's probably wrong images path.

Try cal = StereoCalibration(r'C:/Users/William/hello/images')

As a last resort, change lines 28 and 29 to your working path.

See ya.
